version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    command: "redis-server"
  sidekiq:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    command: bash -c "bundle exec sidekiq -C config/sidekiq.yml.erb"
    depends_on:
      - db
      - redis
  production:
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/espatifo_production
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    depends_on:
      - production
    ports:
      - 80:80
