AllCops:
  TargetRubyVersion: 2.6
  EnabledByDefault: true
  Exclude:
    - 'Rakefile'
    - 'Gemfile'
    - 'config.ru'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'bin/*'

Style/Copyright:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/LineLength:
  Enabled: false
